import { Article, Dashboard } from '@/lib/types';
export type { Article, Dashboard };

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'Крупное обновление в мире технологий',
    snippet: 'Компания Apple представила новую линейку продуктов...',
    content: 'Компания Apple представила новую линейку продуктов с революционными функциями...',
    source_url: 'https://techcrunch.com/article1',
    image_url: 'https://picsum.photos/800/400?random=1',
    created_at: '2024-03-20T10:00:00Z',
    tags: ['Технологии', 'Apple', 'Инновации']
  },
  {
    id: '2',
    title: 'Новые тренды в мировой экономике',
    snippet: 'Эксперты прогнозируют значительные изменения в мировой экономике...',
    content: 'Эксперты прогнозируют значительные изменения в мировой экономике...',
    source_url: 'https://bloomberg.com/article2',
    image_url: 'https://picsum.photos/800/400?random=2',
    created_at: '2024-03-19T15:30:00Z',
    tags: ['Экономика', 'Тренды', 'Прогнозы']
  },
  {
    id: '3',
    title: 'Прорыв в медицинских исследованиях',
    snippet: 'Ученые объявили о важном открытии в области лечения рака...',
    content: 'Ученые объявили о важном открытии в области лечения рака...',
    source_url: 'https://nature.com/article3',
    image_url: 'https://picsum.photos/800/400?random=3',
    created_at: '2024-03-18T09:15:00Z',
    tags: ['Медицина', 'Исследования', 'Здоровье']
  },
  {
    id: '4',
    title: 'Новый прорыв в квантовых вычислениях',
    snippet: 'Ученые достигли нового рекорда в квантовой супрематии',
    description: 'Исследователи из Google и IBM объявили о значительном прогрессе в области квантовых вычислений, достигнув нового рекорда в квантовой супрематии.',
    content: 'Подробное описание исследования и его значение для будущего вычислений...',
    image_url: 'https://picsum.photos/800/400?random=4',
    url: 'https://example.com/quantum-computing',
    published_at: '2024-03-15T10:00:00Z',
    created_at: '2024-03-15T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
    dashboard_key: 'tech',
    source: 'Nature',
    author: 'Dr. John Smith',
    views: 1200,
    likes: 85,
    tags: ['Технологии', 'Наука', 'Искусственный интеллект']
  },
  {
    id: '5',
    title: 'Открытие новой экзопланеты',
    snippet: 'Астрономы обнаружили потенциально обитаемую планету',
    description: 'Международная команда астрономов обнаружила новую экзопланету, которая может быть пригодна для жизни.',
    content: 'Детальное описание открытия и его значение для поиска жизни во Вселенной...',
    image_url: 'https://picsum.photos/800/400?random=5',
    url: 'https://example.com/exoplanet',
    published_at: '2024-03-14T15:30:00Z',
    created_at: '2024-03-14T15:30:00Z',
    updated_at: '2024-03-14T15:30:00Z',
    dashboard_key: 'science',
    source: 'Science',
    author: 'Dr. Sarah Johnson',
    views: 1500,
    likes: 120,
    tags: ['Космос', 'Наука']
  },
  {
    id: '6',
    title: 'Этический кодекс для искусственного интеллекта',
    snippet: 'Международная группа экспертов представила новые принципы этики ИИ',
    description: 'Ведущие специалисты в области искусственного интеллекта разработали новый этический кодекс, который должен регулировать развитие и применение ИИ в различных сферах жизни. Документ включает в себя принципы прозрачности, безопасности и ответственности при разработке и использовании ИИ-систем.',
    content: 'Подробный анализ этических принципов и их практического применения...',
    url: 'https://example.com/ai-ethics',
    published_at: '2024-03-13T09:15:00Z',
    created_at: '2024-03-13T09:15:00Z',
    updated_at: '2024-03-13T09:15:00Z',
    dashboard_key: 'tech',
    source: 'MIT Technology Review',
    author: 'Jane Wilson',
    views: 2000,
    likes: 150,
    tags: ['Искусственный интеллект', 'Этика', 'Технологии']
  },
  {
    id: '7',
    title: 'Революция в квантовых вычислениях',
    snippet: 'Компания IBM представила новый квантовый процессор с 1000 кубитами',
    description: 'IBM представила новый квантовый процессор, содержащий 1000 кубитов. Это достижение знаменует собой важный шаг в развитии квантовых вычислений.',
    content: 'Подробное описание нового процессора и его возможностей...',
    image_url: 'https://picsum.photos/800/400?random=7',
    url: 'https://example.com/article4',
    published_at: '2024-05-05T16:52:11Z',
    created_at: '2024-05-05T16:52:11Z',
    updated_at: '2024-05-05T16:52:11Z',
    dashboard_key: 'd_20250505165211_9',
    source: 'IBM Research',
    author: 'Dr. Michael Brown',
    views: 1800,
    likes: 130,
    tags: ['Технологии', 'Искусственный интеллект', 'Инновации']
  },
  {
    id: '8',
    title: 'Будущее энергетики: перспективы и вызовы',
    snippet: 'Анализ глобальных трендов в энергетическом секторе',
    description: 'Глобальный энергетический сектор стоит на пороге значительных изменений. Переход к возобновляемым источникам энергии, развитие технологий хранения энергии и децентрализация энергосистем создают новые возможности и вызовы для индустрии.',
    content: 'Детальный анализ текущих трендов и прогнозов развития энергетики...',
    image_url: 'https://picsum.photos/800/400?random=8',
    url: 'https://example.com/energy-future',
    published_at: '2024-03-12T14:20:00Z',
    created_at: '2024-03-12T14:20:00Z',
    updated_at: '2024-03-12T14:20:00Z',
    dashboard_key: 'tech',
    source: 'Energy Review',
    author: 'David Chen',
    views: 1600,
    likes: 110,
    tags: ['Энергетика', 'Технологии', 'Экология']
  },
  {
    id: '9',
    title: 'Прорыв в лечении рака',
    snippet: 'Ученые разработали новый метод иммунотерапии с 90% эффективностью',
    description: 'Ученые разработали новый метод иммунотерапии, который показал эффективность 90% в клинических испытаниях.',
    content: 'Подробное описание нового метода лечения...',
    image_url: 'https://picsum.photos/800/400?random=9',
    url: 'https://example.com/article6',
    published_at: '2024-05-05T16:52:11Z',
    created_at: '2024-05-05T16:52:11Z',
    updated_at: '2024-05-05T16:52:11Z',
    dashboard_key: 'd_20250505165211_9',
    source: 'Medical Journal',
    author: 'Dr. Emily White',
    views: 2500,
    likes: 200,
    tags: ['Медицина', 'Наука', 'Инновации']
  },
  {
    id: '10',
    title: 'Цифровая трансформация образования',
    snippet: 'Как технологии меняют процесс обучения',
    description: 'Цифровые технологии кардинально меняют подход к образованию. Онлайн-платформы, искусственный интеллект и виртуальная реальность создают новые возможности для персонализированного обучения и делают образование более доступным.',
    content: 'Анализ влияния цифровых технологий на образование...',
    url: 'https://example.com/digital-education',
    published_at: '2024-03-11T11:45:00Z',
    created_at: '2024-03-11T11:45:00Z',
    updated_at: '2024-03-11T11:45:00Z',
    dashboard_key: 'tech',
    source: 'Education Today',
    author: 'Prof. Robert Green',
    views: 1700,
    likes: 140,
    tags: ['Образование', 'Технологии', 'Инновации']
  },
  {
    id: '11',
    title: 'Революция в хранении данных',
    snippet: 'Ученые создали новый тип памяти с плотностью 1 петабайт на квадратный сантиметр',
    description: 'Исследователи разработали новый тип памяти, способный хранить 1 петабайт данных на квадратный сантиметр.',
    content: 'Подробное описание новой технологии хранения данных...',
    image_url: 'https://picsum.photos/800/400?random=11',
    url: 'https://example.com/article8',
    published_at: '2024-05-05T16:52:11Z',
    created_at: '2024-05-05T16:52:11Z',
    updated_at: '2024-05-05T16:52:11Z',
    dashboard_key: 'd_20250505165211_9',
    source: 'Tech Review',
    author: 'Dr. Lisa Wang',
    views: 1900,
    likes: 160,
    tags: ['Технологии', 'Инновации']
  },
  {
    id: '12',
    title: 'Новый этап в освоении космоса',
    snippet: 'Частная компания успешно запустила первую коммерческую космическую станцию',
    description: 'Частная космическая компания успешно вывела на орбиту первую коммерческую космическую станцию.',
    content: 'Подробное описание запуска и планов компании...',
    image_url: 'https://picsum.photos/800/400?random=12',
    url: 'https://example.com/article9',
    published_at: '2024-05-05T16:52:11Z',
    created_at: '2024-05-05T16:52:11Z',
    updated_at: '2024-05-05T16:52:11Z',
    dashboard_key: 'd_20250505165211_9',
    source: 'Space News',
    author: 'James Anderson',
    views: 2200,
    likes: 180,
    tags: ['Космос', 'Технологии', 'Инновации']
  },
  {
    id: '13',
    title: 'Новая революция в технологиях',
    snippet: 'Ученые объявили о важном открытии в области квантовых вычислений',
    description: 'Новое исследование открывает перспективы в области квантовых вычислений',
    content: 'Ученые объявили о важном открытии в области квантовых вычислений',
    image_url: 'https://picsum.photos/800/400?random=13',
    url: 'https://example.com/quantum-computing',
    published_at: '2024-03-10T10:00:00Z',
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-03-10T10:00:00Z',
    dashboard_key: 'tech',
    source: 'Nature',
    author: 'Dr. John Doe',
    views: 1500,
    likes: 100,
    tags: ['Технологии', 'Наука', 'Инновации']
  },
  {
    id: '14',
    title: 'Открытие новой экзопланеты',
    snippet: 'Астрономы обнаружили потенциально обитаемую планету',
    description: 'Международная команда астрономов обнаружила новую экзопланету, которая может быть пригодна для жизни',
    content: 'Детальное описание открытия и его значение для поиска жизни во Вселенной',
    image_url: 'https://picsum.photos/800/400?random=14',
    url: 'https://example.com/exoplanet',
    published_at: '2024-03-09T15:30:00Z',
    created_at: '2024-03-09T15:30:00Z',
    updated_at: '2024-03-09T15:30:00Z',
    dashboard_key: 'science',
    source: 'Science',
    author: 'Dr. Jane Smith',
    views: 1800,
    likes: 120,
    tags: ['Космос', 'Наука']
  },
  {
    id: '15',
    title: 'Этический кодекс для искусственного интеллекта',
    snippet: 'Международная группа экспертов представила новые принципы этики ИИ',
    description: 'Ведущие специалисты в области искусственного интеллекта разработали новый этический кодекс, который должен регулировать развитие и применение ИИ в различных сферах жизни',
    content: 'Подробный анализ этических принципов и их практического применения',
    url: 'https://example.com/ai-ethics',
    published_at: '2024-03-08T09:15:00Z',
    created_at: '2024-03-08T09:15:00Z',
    updated_at: '2024-03-08T09:15:00Z',
    dashboard_key: 'tech',
    source: 'MIT Technology Review',
    author: 'Jane Wilson',
    views: 2000,
    likes: 140,
    tags: ['Искусственный интеллект', 'Этика', 'Технологии']
  },
  {
    id: '16',
    title: 'Революция в квантовых вычислениях',
    snippet: 'Компания IBM представила новый квантовый процессор с 1000 кубитами',
    description: 'IBM представила новый квантовый процессор, содержащий 1000 кубитов',
    content: 'Подробное описание нового процессора и его возможностей',
    image_url: 'https://picsum.photos/800/400?random=16',
    url: 'https://example.com/article4',
    published_at: '2024-05-05T16:52:11Z',
    created_at: '2024-05-05T16:52:11Z',
    updated_at: '2024-05-05T16:52:11Z',
    dashboard_key: 'd_20250505165211_9',
    source: 'IBM Research',
    author: 'Dr. Michael Brown',
    views: 1800,
    likes: 130,
    tags: ['Технологии', 'Искусственный интеллект', 'Инновации']
  },
  {
    id: '17',
    title: 'Будущее энергетики: перспективы и вызовы',
    snippet: 'Анализ глобальных трендов в энергетическом секторе',
    description: 'Глобальный энергетический сектор стоит на пороге значительных изменений',
    content: 'Детальный анализ текущих трендов и прогнозов развития энергетики',
    image_url: 'https://picsum.photos/800/400?random=17',
    url: 'https://example.com/energy-future',
    published_at: '2024-03-07T14:20:00Z',
    created_at: '2024-03-07T14:20:00Z',
    updated_at: '2024-03-07T14:20:00Z',
    dashboard_key: 'tech',
    source: 'Energy Review',
    author: 'David Chen',
    views: 1600,
    likes: 110,
    tags: ['Энергетика', 'Технологии', 'Экология']
  },
  {
    id: '18',
    title: 'Прорыв в лечении рака',
    snippet: 'Ученые разработали новый метод иммунотерапии с 90% эффективностью',
    description: 'Ученые разработали новый метод иммунотерапии, который показал эффективность 90% в клинических испытаниях',
    content: 'Подробное описание нового метода лечения',
    image_url: 'https://picsum.photos/800/400?random=18',
    url: 'https://example.com/article6',
    published_at: '2024-05-05T16:52:11Z',
    created_at: '2024-05-05T16:52:11Z',
    updated_at: '2024-05-05T16:52:11Z',
    dashboard_key: 'd_20250505165211_9',
    source: 'Medical Journal',
    author: 'Dr. Emily White',
    views: 2500,
    likes: 200,
    tags: ['Медицина', 'Наука', 'Инновации']
  },
  {
    id: '19',
    title: 'Цифровая трансформация образования',
    snippet: 'Как технологии меняют процесс обучения',
    description: 'Цифровые технологии кардинально меняют подход к образованию',
    content: 'Анализ влияния цифровых технологий на образование',
    url: 'https://example.com/digital-education',
    published_at: '2024-03-06T11:45:00Z',
    created_at: '2024-03-06T11:45:00Z',
    updated_at: '2024-03-06T11:45:00Z',
    dashboard_key: 'tech',
    source: 'Education Today',
    author: 'Prof. Robert Green',
    views: 1700,
    likes: 140,
    tags: ['Образование', 'Технологии', 'Инновации']
  },
  {
    id: '20',
    title: 'Революция в хранении данных',
    snippet: 'Ученые создали новый тип памяти с плотностью 1 петабайт на квадратный сантиметр',
    description: 'Исследователи разработали новый тип памяти, способный хранить 1 петабайт данных на квадратный сантиметр',
    content: 'Подробное описание новой технологии хранения данных',
    image_url: 'https://picsum.photos/800/400?random=20',
    url: 'https://example.com/article8',
    published_at: '2024-05-05T16:52:11Z',
    created_at: '2024-05-05T16:52:11Z',
    updated_at: '2024-05-05T16:52:11Z',
    dashboard_key: 'd_20250505165211_9',
    source: 'Tech Review',
    author: 'Dr. Lisa Wang',
    views: 1900,
    likes: 160,
    tags: ['Технологии', 'Инновации']
  }
];

export const mockDashboard: Dashboard = {
  id: '1',
  key: 'd_20250505165211_9',
  created_at: '2024-05-05T16:52:11Z',
  articles: ['1', '2', '3'],
  public: true
};

// Функция для получения случайной статьи
export const getRandomArticle = (): Article => {
  return mockArticles[Math.floor(Math.random() * mockArticles.length)];
};

// Функция для получения случайного дашборда
export const getRandomDashboard = (): Dashboard => {
  return mockDashboard;
};

// Функция для получения статей по дашборду
export const getArticlesByDashboard = (dashboard: Dashboard): Article[] => {
  return mockArticles.filter(article => dashboard.articles.includes(article.id));
};